### ISSUE TITLE
how to check card type from decrypted details

### ISSUE THREAD

**Issue by Tusshark** [chokepoint/DUKPT#1]
hi
Actually , in my side encryption and decryption of card details or track1 and track2 details is correct.
but after decryption process i am unable to find out which card is swiped . So please give me the resolution for that how i am verify card type from decrypted track1 or track2 details.

**Comment by chokepoint** [comment]
This project only deals with the keying for the DUKPT algorithm. I can't comment on your implementation due to lack of knowledge of your product and code as a whole.
