### ISSUE TITLE
Passing in BDK

### ISSUE THREAD

**Issue by dustindoucette** [chokepoint/DUKPT#4]
Hi @chokepoint, just had a quick question concerning this program. I am trying to find a way to pass in a BDK instead of the server generating one. Would you be able to tell me how to initialize the server in a way that allows a BDK passed in?

Thank you in advance,
Dustin

**Comment by chokepoint** [comment]
You should be able to pass the bdk to the DUKPT class during the initialization by specifying the optional bdk=var_with_bdk_to_import_here.

https://github.com/chokepoint/DUKPT/blob/5d40401d267684591856189bf90cfc8b83b3fca6/dukpt.py#L142

**Comment by chokepoint** [comment]
Did this help? I'll leave this open another week before closing it. Cheers.

**Comment by dustindoucette** [comment]
Hi @chokepoint, thank you very much for the reply and answer! Works perfectly 👌🏼, Thanks, Dustin
